### ISSUE TITLE
No Appropiate documentation

### ISSUE THREAD

**Issue by tusharcoder** [haydenbr/webrtc-video-chat#1]
I am trying to run your solution in my local network, I found no information what to enter the values in STUN SERVER, TURN SERVER, USERNAME, PASSWORD

So unable to run. Kindly Help

**Comment by lechuhuuha** [comment]
> I am trying to run your solution in my local network, I found no information what to enter the values in STUN SERVER, TURN SERVER, USERNAME, PASSWORD
> 
> So unable to run. Kindly Help

for stun or turn you can build your own using coturn for turn and stuntman for stun
username is for room name so other pp can join your room
turn username and password is for turn server

**Comment by haydenbr** [comment]
@tusharcoder sorry I'm just now seeing this 😬. For running locally, just follow the steps in the README, run `npm start` to start the signaling server and client server. Then follow the steps to build and run the turn server. (You'll need go installed).

From there, click the "local" button, enter a user name, which is just your display name when you join the call, and click join. You can then do the same from multiple browser tabs to join the WebRTC call multiple times to simulate what it would be like having multiple people in the call. If you use ssl certificates for the signaling server and client server when running locally, I think you can then join the call from any device on your local network, which is kind of fun.

Anyways, thanks for reaching out with your question. Based on your feedback, I think I can make some clarifications in the README. Let me know if you have anymore questions!
